### ISSUE TITLE
splat color issue in builds

### ISSUE THREAD

**Issue by unitycoder** [ninjamode/Unity-VR-Gaussian-Splatting#2]
works fine in editor,
but build looks like this:
![image](https://github.com/user-attachments/assets/67b2bf40-ea98-4081-9be2-17871c8b6358)

2022.3.45f1 + URP + VR (openxr multipass)

*there is this message in player.log, if related?
```
Texture compression not available at runtime
UnityEngine.Logger:Log(LogType, Object)
UnityEngine.Debug:LogError(Object)
GaussianSplatting.Runtime.GaussianImageCreator:CreateColorData(NativeArray`1, ColorFormat)
GaussianSplatting.Runtime.GaussianSplatRenderer:UpdateRessources()
GaussianSplatting.Runtime.GaussianSplatRenderer:Update()
```

**Comment by unitycoder** [comment]
ok, it was due to using that compressed format (BC7)
![image](https://github.com/user-attachments/assets/a8527723-d204-4c74-8630-e0c7901dbbfe)

**Comment by ninjamode** [comment]
Compression to texture is not supported. This is due to the multi-layer capability and the need to recompress multiple layer combinations at runtime, however the image compression APIs are only available in the editor. Note that this is not strictly related to VR support, so you could adjust the code to initially create the image in the editor and load that later
